"""m6 flagged + audit_log

Revision ID: 93763f1d66aa
Revises: 2af7d2049bbe
Create Date: 2026-07-10 12:02:09.656627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93763f1d66aa'
down_revision: Union[str, None] = '2af7d2049bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_username'), ['username'], unique=False)

    with op.batch_alter_table('eval_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_eval_result_flagged'), ['flagged'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_result_flagged'))
        batch_op.drop_column('flagged')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_username'))
        batch_op.drop_index(batch_op.f('ix_audit_log_path'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
