"""baseline schema m0-m4

Revision ID: fd98d7b1350c
Revises: 
Create Date: 2026-07-10 01:14:01.498049
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'fd98d7b1350c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_log_batch_id'), ['batch_id'], unique=False)

    op.create_table('llm_model',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('adapter_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('api_key_env', sa.String(length=64), nullable=True),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key')
    )
    with op.batch_alter_table('llm_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_model_enabled'), ['enabled'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_enabled'), ['enabled'], unique=False)

    op.create_table('run_batch',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('judge_enabled', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_batch_status'), ['status'], unique=False)

    op.create_table('schedule_config',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=True),
    sa.Column('model_ids', sa.JSON(), nullable=True),
    sa.Column('judge_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_config_enabled'), ['enabled'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('qa_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('question_snapshot', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('asked_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.String(length=512), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['run_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_log_asked_at'), ['asked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_log_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_log_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_qa_log_q_m_t', ['question_id', 'model_id', 'asked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_log_question_id'), ['question_id'], unique=False)

    op.create_table('standard_answer',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_answer_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_answer_question_id'), ['question_id'], unique=False)

    op.create_table('eval_result',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('qa_log_id', sa.BigInteger(), nullable=False),
    sa.Column('judge_model', sa.String(length=32), nullable=False),
    sa.Column('standard_answer_snapshot', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('correctness_score', sa.Integer(), nullable=True),
    sa.Column('pollution_level', sa.String(length=16), nullable=True),
    sa.Column('deviation_level', sa.String(length=16), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['qa_log_id'], ['qa_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_result_pollution_level'), ['pollution_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_result_qa_log_id'), ['qa_log_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_eval_result_verdict'), ['verdict'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_result_verdict'))
        batch_op.drop_index(batch_op.f('ix_eval_result_qa_log_id'))
        batch_op.drop_index(batch_op.f('ix_eval_result_pollution_level'))

    op.drop_table('eval_result')
    with op.batch_alter_table('standard_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_answer_question_id'))
        batch_op.drop_index(batch_op.f('ix_standard_answer_is_active'))

    op.drop_table('standard_answer')
    with op.batch_alter_table('qa_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_log_question_id'))
        batch_op.drop_index('ix_qa_log_q_m_t')
        batch_op.drop_index(batch_op.f('ix_qa_log_model_id'))
        batch_op.drop_index(batch_op.f('ix_qa_log_batch_id'))
        batch_op.drop_index(batch_op.f('ix_qa_log_asked_at'))

    op.drop_table('qa_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))

    op.drop_table('user')
    with op.batch_alter_table('schedule_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_config_enabled'))

    op.drop_table('schedule_config')
    with op.batch_alter_table('run_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_batch_status'))

    op.drop_table('run_batch')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_enabled'))
        batch_op.drop_index(batch_op.f('ix_question_category'))

    op.drop_table('question')
    with op.batch_alter_table('llm_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_model_enabled'))

    op.drop_table('llm_model')
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_log_batch_id'))

    op.drop_table('alert_log')
    # ### end Alembic commands ###
